insert into raca (name) values ('Vira Lata');
insert into raca (name) values ('Pitbull');
insert into raca (name) values ('Pastor Alemão');
insert into raca (name) values ('Chiuaua');
insert into raca (name) values ('Chow Chow');
insert into raca (name) values ('Doberman');
insert into raca (name) values ('Husky');
insert into raca (name) values ('Basse');
insert into raca (name) values ('Dalmata');
insert into raca (name) values ('Afegão');
insert into raca (name) values ('Airedale');
insert into raca (name) values ('Akita');
insert into raca (name) values ('Boiadeiro Australiano');
insert into raca (name) values ('Golden');
insert into raca (name) values ('Grande Boiadeiro Suiço');
insert into raca (name) values ('Galgo Escocês');
insert into raca (name) values ('Greyhound');
insert into raca (name) values ('Grifo da Bélgica');
insert into raca (name) values ('ShihTzu');
insert into raca (name) values ('King Charles');