insert into cachorro (name, cor, raca_id) values ('Rodolfo Mosby', 'Blue', 14);
insert into cachorro(name, cor, raca_id) values ('Catha McCartan', 'Maroon', 2);
insert into cachorro (name, cor, raca_id) values ('Cully Leathley', 'Khaki', 20);
insert into cachorro (name, cor, raca_id) values ('Gardie Cradoc', 'Yellow', 3);
insert into cachorro (name, cor, raca_id) values ('Susie O''Flynn', 'Mauv', 14);
insert into cachorro (name, cor, raca_id) values ('Hyacinth Enstone', 'Fuscia', 19);
insert into cachorro (name, cor, raca_id) values ('Stefanie Sterte', 'Maroon', 18);
insert into cachorro (name, cor, raca_id) values ('Artie Capon', 'Puce', 16);
insert into cachorro (name, cor, raca_id) values ('Katharina Matitiaho', 'Green', 12);
insert into cachorro (name, cor, raca_id) values ('Buddie Foffano', 'Purple', 7);
insert into cachorro (name, cor, raca_id) values ('Maison Karpenko', 'Purple', 5);
insert into cachorro(name, cor, raca_id) values ('Brenn Fenck', 'Red', 4);
insert into cachorro(name, cor, raca_id) values ('Licha Hayford', 'Green', 2);
insert into cachorro(name, cor, raca_id) values ('Mose Loreit', 'Blue', 16);
insert into cachorro(name, cor, raca_id) values ('Vern Quincee', 'Teal', 11);
insert into cachorro(name, cor, raca_id) values ('Weider Muckeen', 'Maroon', 12);
insert into cachorro(name, cor, raca_id) values ('Allan Dawid', 'Teal', 1);
insert into cachorro (name, cor, raca_id) values ('Thurstan Palatino', 'Fuscia', 5);
insert into cachorro (name, cor, raca_id) values ('Grissel Cicchinelli', 'Purple', 18);
insert into cachorro (name, cor, raca_id) values ('Bella Margett', 'Blue', 17);